version: "3"
services:

  frontend:
   
    build: .
    ports:
     - 3006:80
    networks:
      - coursenetwork
    depends_on:
      - backend

  dbservice:
    
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #MYSQL_USERNAME=username

    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306
    networks:
      - coursenetwork

  backend:
    
    build: ./backend
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/coursedb?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root

    ports:
      - 9090:9090
    networks:
       - coursenetwork  

networks:
 coursenetwork:
  
    
     
